services:
  minecraft:
    image: itzg/minecraft-server:latest
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      MEMORY: 4G
      SERVER_NAME: "Detritus Minecraft Server"
      MODE: survival
      PVP: true
      DIFFICULTY: normal
      HARDCORE: false
      MAX_PLAYERS: 20
      VIEW_DISTANCE: 12
      SIMULATION_DISTANCE: 12
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./data:/data
