services:
  resilio-sync:
    image: resilio/sync
    restart: unless-stopped
    ports:
      - 8888:8888
      - 55555:55555
    volumes:
      - ./data:/mnt/sync
    environment:
      - TZ=UTC
      - USER_ID=1000
      - GROUP_ID=1000
