# https://hub.docker.com/r/hexlo/terraria-server-docker

services:
  terraria-server:
    image: ghcr.io/hexlo/terraria-server-docker:latest
    container_name: terraria-server
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 7779:7777
    volumes:
      - ./data:/root/.local/share/Terraria/Worlds/
    environment:
      - world=/root/.local/share/Terraria/Worlds/world1.wld
      - autocreate=2
      - worldname=world1
      - difficulty=1
      - maxplayers=8
      - port=7777
      - password=detritus
      - motd="Welcome to detritus's server! :)"
