services:
  lupa_database:
    image: mysql:debian
    command: --default-authentication-plugin=mysql_native_password --skip-log-bin
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=lupa
      - MYSQL_USER=lupa
      - MYSQL_USER_HOST=%
      - MYSQL_PASSWORD=userpwd
      - TX=America/Toronto
  #    ports:
  #      - "8002:3306"

  lupa_wordpress:
    image: wordpress:latest
    depends_on:
      - lupa_database
    volumes:
      - ./wp/:/var/www/html/
    ports:
      - "8001:80"
    restart: always
    environment:
      - WORDPRESS_DB_HOST=lupa_database
      - WORDPRESS_DB_NAME=lupa
      - WORDPRESS_DB_USER=lupa
      - WORDPRESS_DB_PASSWORD=userpwd
