services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - "8096:8096"
    volumes:
      - ./config:/config
      - ./cache:/cache
      #- /path/to/media:/media
      #- /path/to/media2:/media2:ro
    restart: "unless-stopped"

    ## Accelerated video
    #group_add:
    #  - "122" # Change this to match your "render" host group id and remove this comment
    #devices:
    #  - /dev/dri/renderD128:/dev/dri/renderD128

    # Optional - alternative address used for autodiscovery
    #environment:
    #- JELLYFIN_PublishedServerUrl=http://example.com
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - "host.docker.internal:host-gateway"
