services:
  valheim:
    image: ghcr.io/lloesche/valheim-server
    cap_add:
      - sys_nice
    environment:
      SERVER_NAME: Detritus
      WORLD_NAME: World
      SERVER_PASS: FooBar
      SERVER_PUBLIC: false
      # Presets: normal, casual, easy, hard, hardcore, immersive, hammer
      SERVER_ARGS: "-crossplay -preset easy"
    volumes:
      - ./config:/config/
      - valheim-data:/opt/valheim
    ports:
      - "2456-2457:2456-2457/udp"
      - "9001:9001/tcp"
    restart: unless-stopped
    stop_grace_period: 2m

volumes:
  valheim-data:
    name: valheim-data
