services:
  satisfactory-server:
    container_name: "satisfactory-server"
    hostname: "satisfactory-server"
    image: "wolveix/satisfactory-server:latest"
    network_mode: host
    volumes:
      - "./config:/config"
    environment:
      - MAXPLAYERS=4
      - ROOTLESS=false
      - STEAMBETA=false
      - DISABLESEASONALEVENTS=true
    restart: unless-stopped

volumes:
  satisfactory-data:
    name: satisfactory-data
