services:
  npm:
    image: "jc21/nginx-proxy-manager:latest"
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./npm-data:/data
      - ./npm-ssl:/etc/letsencrypt
    environment:
      DISABLE_IPV6: "true"
