services:
  bedrock:
    image: itzg/minecraft-bedrock-server
    restart: unless-stopped
    environment:
      EULA: "TRUE"
      SERVER_NAME: Detritus
      GAMEMODE: survival
      DIFFICULTY: normal
      MAX_PLAYERS: 10
      VIEW_DISTANCE: 16
      TICK_DISTANCE: 16
    ports:
      - 19132:19132/udp
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
